### ISSUE TITLE
MDM user scope assignment

### ISSUE THREAD

**Issue by Martony78** [SMSAgentSoftware/IntuneAssignmentsReport#1]
Should be useful to also get this info

**Comment by SMSAgentSoftware** [comment]
Thanks for raising the issue. Unfortunately the Graph endpoint that can return this information doesn't support application permissions, therefore it can't be used with automation currently. Ref: https://learn.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&tabs=http#permissions

There is an undocumented API that can also be used to retrieve this information (main.iam.ad.ext.azure.com/api/MdmApplications) but afaik this doesn't support app permissions either.
